# Generated by Django 2.2 on 2019-05-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('abstract', models.TextField()),
                ('feature_a', models.IntegerField()),
                ('feature_b', models.IntegerField()),
                ('feature_c', models.IntegerField()),
                ('feature_d', models.IntegerField()),
                ('feature_e', models.IntegerField()),
            ],
        ),
    ]
