# Generated by Django 2.2 on 2019-05-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='record',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
