# Generated by Django 2.2 on 2019-05-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20190511_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='feature_a',
            new_name='adverse_effect',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='feature_b',
            new_name='identifiable_drug',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='feature_c',
            new_name='identifiable_patient',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='feature_d',
            new_name='mah',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='feature_e',
            new_name='precondition',
        ),
        migrations.AlterField(
            model_name='record',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
