# Generated by Django 2.2 on 2019-05-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20190511_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='adverse_effect',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='identifiable_drug',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='identifiable_patient',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='mah',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='precondition',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
